#logging:
#  level:
#    web: debug
#    ru.vm.cookieextractor: info
server:
  error:
    includeMessage: ALWAYS
  port: 9421
cookie:
  clients:
    main:
      files:
        sh:
          format: shell
          path: cookies/main.sh
        json:
          format: json
          path: cookies/cookies.json
