package ru.vm.cookieextractor.server

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(CookieExtractorProperties::class)
class CookieExtractorConfiguration